
/*----------- 1. " Database Exploration" ---------------------------------------- */


--------- Explore All Objects in the database


SELECT *
FROM INFORMATION_SCHEMA.TABLES ;

SELECT *
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'master';

show tables from master;



--------- Explore All columns in the database

SELECT *
FROM INFORMATION_SCHEMA.columns ;

SELECT *
FROM INFORMATION_SCHEMA.columns
where table_schema ="master" ;

SELECT *
FROM INFORMATION_SCHEMA.columns
where table_name = "customers" ;



/*-------------------- 2. " Dimensions Exploration " ----------------------------------- */



		                --- Customers  table ---
        
        

---- Explore All countries our customers come from ------

select distinct country from customers ;


------- Explore gender count of our customers ----------

select gender ,count(gender) as total_count  from customers 
group by gender ;


------- Explore marital_status count of customers ----------------

select marital_status, count(marital_status) as total_count from customers
group by marital_status ;



				       ------------ Products table -------------
                  
   
   ---- Explore  Categories in the products 
   
    select distinct category , subcategory , product_name from products ;
    
    select distinct category from products ;
    
    
    
     /* ----------------- 3." Date Exploration " ---------------- */
     
     
--- finding the date of the first and last order -------

select min(order_date) as first_order_date,
max(order_date) as last_order_date ,
timestampdiff(year ,min(order_date),max(order_date)) as range_difference from  sales ;


---- finding the youngest and the oldest customer ------


select 
min(birthdate) oldest_birthdaydate,
timestampdiff(year,min(birthdate),curdate()) as oldest_age,
max(birthdate) as youngest_birthday,
timestampdiff(year,max(birthdate),curdate()) as young_age
from customers ;


/*  ----------------- 4. " Measures Exploration " --------------------- */


--- finding the total sales ---------

 select sum(sales_amount) from sales ;
 
 
 --- finding how many items are sold -------
 
select sum(quantity) as total_quantity from sales ;

----- finding the average selling price ----------

select avg(price) as average_selling_price from sales ;


----- finding the total number of orders ------

select count(order_number) as total_orders from sales ;
select count(distinct order_number) as total_orders from sales ;


---- finding the total number of products -------

select count(product_name) as total_product from products ;


----- finding the total number of customers ------

select count(customer_key) as total_customers from customers ;
select count(distinct(customer_key)) as total_customers from customers ;

---- finding the total number of customers that has placed an order -----

 select count(distinct customer_key) as order_placed_customers from sales ;




----- Generating  a Report that shows all key metrics of the busines -----


 select "Total sales"  as measue_name ,round(sum(sales_amount),0) as measure_value from sales 
union all
select "Total quantity" as measure_name ,round(sum(quantity),0) as measure_name from sales 
union all
select "Average price " as measure_name  ,round(avg(price),0)  from sales 
union all
select "Total_No_orders " as measure_name, round(count(distinct order_number),0)  from sales 
union all
select "Total_No_products " as measure_name ,round(count(distinct product_name),0) from products 
union all
select "Total_No_customers" as measure_name, round(count(distinct(customer_key)),0)  from customers ;



--------------- 5. " Magnitude " ---------------------------

/* comparing the measure values by categories 
it helps to understand the importance of different categories*/


--- finding total customers by countries ------


select country, count(customer_key) as total_customers 
from customers group by country order by total_customers desc ;


--- finding total customers by gender -----


select gender, count(customer_key) as total_customers 
from customers group by gender order by total_customers desc ;


---- finding total products  by category -----


select category,count(product_name) as total_product 
from products group by category order by total_product desc ;


---- finding the average cost in each category ---------


select category,round(avg(cost),0) as average_cost
from products group by category order by average_cost desc ;


--- finding what is the total revenue generated for each category -----

select p.category,sum(s.sales_amount) as total_revenue
from sales as s
left join products as p
on p.product_key = s.product_key
group by p.category
order by total_revenue desc ;


--- what is the total revenue generated by each customer -------
															              /* ( High cardinality Dimension
																		  Dimension with large number of unique values ) */
                                                             
select c.customer_id ,c.first_name,c.last_name,
sum(s.sales_amount) as total_revenue from
sales as s
left join customers as c
on c.customer_key=s.customer_key
group by c.customer_id,c.first_name,c.last_name order by total_revenue desc ;


------ what is the distribution of items sold across countries -----
                                                                      /* ( Low cardinality Dimension
																		  Dimension with few unique values ) */
select c.country,
sum(s.quantity) as total_quantity_sold from
sales as s
left join customers as c                                                
on c.customer_key=s.customer_key                                          
group by c.country order by total_quantity_sold desc ;



/*-------------------- 6. " Ranking " -------------------------------- */


---- finding which top 5 product generate the highest revenue ------

select p.product_name ,
sum( s.sales_amount) as total_revenue from 
sales as s
left join products as p
on p.product_key=s.product_key
group by p.product_name  order by total_revenue desc limit 5;


---- finding the 5 worst - performing products in terms of sales -------

select p.product_name ,
sum( s.sales_amount) as total_revenue from 
sales as s
left join products as p
on p.product_key=s.product_key
group by p.product_name  order by total_revenue  limit 5;


---- finding top 10 customers who have generated the highest revenue ----------

select * from 
( select c.first_name,c.last_name,
sum(s.sales_amount) as total_revenue,
row_number() over(order by sum(s.sales_amount) desc) as rank_no
from
sales as s
left join customers as c
on c.customer_key=s.customer_key
group by c.first_name,c.last_name order by total_revenue desc  limit 10) as temp 
where rank_no <=10 ;


---- finding  the 3 customers with fewest orders placed ----------


select c.customer_key ,c.first_name,c.last_name,
count(distinct order_number) as total_orders
 from sales as s
left join customers as c
on c.customer_key=s.customer_key
group by c.customer_key ,c.first_name,c.last_name order by total_orders limit 3;








